/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface AnchorFactoryPoseidonInterface extends ethers.utils.Interface {
  functions: {
    "create2Anchor2(bytes32,address,address,uint256,uint32,uint32,address,address,address,address)": FunctionFragment;
    "createAnchor2(address,address,uint256,uint32,uint32,address,address,address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "create2Anchor2",
    values: [
      BytesLike,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createAnchor2",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      string
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "create2Anchor2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAnchor2",
    data: BytesLike
  ): Result;

  events: {};
}

export class AnchorFactoryPoseidon extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AnchorFactoryPoseidonInterface;

  functions: {
    create2Anchor2(
      _salt: BytesLike,
      _verifier: string,
      _hasher: string,
      _denomination: BigNumberish,
      _merkleTreeHeight: BigNumberish,
      _chainID: BigNumberish,
      _token: string,
      _bridge: string,
      _admin: string,
      _handler: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createAnchor2(
      _verifier: string,
      _hasher: string,
      _denomination: BigNumberish,
      _merkleTreeHeight: BigNumberish,
      _chainID: BigNumberish,
      _token: string,
      _bridge: string,
      _admin: string,
      _handler: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  create2Anchor2(
    _salt: BytesLike,
    _verifier: string,
    _hasher: string,
    _denomination: BigNumberish,
    _merkleTreeHeight: BigNumberish,
    _chainID: BigNumberish,
    _token: string,
    _bridge: string,
    _admin: string,
    _handler: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createAnchor2(
    _verifier: string,
    _hasher: string,
    _denomination: BigNumberish,
    _merkleTreeHeight: BigNumberish,
    _chainID: BigNumberish,
    _token: string,
    _bridge: string,
    _admin: string,
    _handler: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    create2Anchor2(
      _salt: BytesLike,
      _verifier: string,
      _hasher: string,
      _denomination: BigNumberish,
      _merkleTreeHeight: BigNumberish,
      _chainID: BigNumberish,
      _token: string,
      _bridge: string,
      _admin: string,
      _handler: string,
      overrides?: CallOverrides
    ): Promise<void>;

    createAnchor2(
      _verifier: string,
      _hasher: string,
      _denomination: BigNumberish,
      _merkleTreeHeight: BigNumberish,
      _chainID: BigNumberish,
      _token: string,
      _bridge: string,
      _admin: string,
      _handler: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    create2Anchor2(
      _salt: BytesLike,
      _verifier: string,
      _hasher: string,
      _denomination: BigNumberish,
      _merkleTreeHeight: BigNumberish,
      _chainID: BigNumberish,
      _token: string,
      _bridge: string,
      _admin: string,
      _handler: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createAnchor2(
      _verifier: string,
      _hasher: string,
      _denomination: BigNumberish,
      _merkleTreeHeight: BigNumberish,
      _chainID: BigNumberish,
      _token: string,
      _bridge: string,
      _admin: string,
      _handler: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    create2Anchor2(
      _salt: BytesLike,
      _verifier: string,
      _hasher: string,
      _denomination: BigNumberish,
      _merkleTreeHeight: BigNumberish,
      _chainID: BigNumberish,
      _token: string,
      _bridge: string,
      _admin: string,
      _handler: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createAnchor2(
      _verifier: string,
      _hasher: string,
      _denomination: BigNumberish,
      _merkleTreeHeight: BigNumberish,
      _chainID: BigNumberish,
      _token: string,
      _bridge: string,
      _admin: string,
      _handler: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
