/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface BadRecipientInterface extends Interface {
  functions: {};

  events: {};
}

export class BadRecipient extends Contract {
  connect(signerOrProvider: Signer | Provider | string): BadRecipient;
  attach(addressOrName: string): BadRecipient;
  deployed(): Promise<BadRecipient>;

  on(event: EventFilter | string, listener: Listener): BadRecipient;
  once(event: EventFilter | string, listener: Listener): BadRecipient;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): BadRecipient;
  removeAllListeners(eventName: EventFilter | string): BadRecipient;
  removeListener(eventName: any, listener: Listener): BadRecipient;

  interface: BadRecipientInterface;

  functions: {};

  filters: {};

  estimate: {};
}
