/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { EventFragment, FunctionFragment, Result } from '@ethersproject/abi';
import { BytesLike } from '@ethersproject/bytes';
import { CallOverrides, Contract, ContractTransaction } from '@ethersproject/contracts';
import { Listener, Provider } from '@ethersproject/providers';
import { BigNumber, BigNumberish, ethers, EventFilter, PopulatedTransaction, Signer } from 'ethers';

interface HasherInterface extends ethers.utils.Interface {
  functions: {
    'MiMCSponge(uint256,uint256)': FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'MiMCSponge', values: [BigNumberish, BigNumberish]): string;

  decodeFunctionResult(functionFragment: 'MiMCSponge', data: BytesLike): Result;

  events: {};
}

export class Hasher extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: HasherInterface;

  functions: {
    MiMCSponge(
      xL_in: BigNumberish,
      xR_in: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      xL: BigNumber;
      xR: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    'MiMCSponge(uint256,uint256)'(
      xL_in: BigNumberish,
      xR_in: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      xL: BigNumber;
      xR: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;
  };

  MiMCSponge(
    xL_in: BigNumberish,
    xR_in: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    xL: BigNumber;
    xR: BigNumber;
    0: BigNumber;
    1: BigNumber;
  }>;

  'MiMCSponge(uint256,uint256)'(
    xL_in: BigNumberish,
    xR_in: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    xL: BigNumber;
    xR: BigNumber;
    0: BigNumber;
    1: BigNumber;
  }>;

  callStatic: {
    MiMCSponge(
      xL_in: BigNumberish,
      xR_in: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      xL: BigNumber;
      xR: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    'MiMCSponge(uint256,uint256)'(
      xL_in: BigNumberish,
      xR_in: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      xL: BigNumber;
      xR: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;
  };

  filters: {};

  estimateGas: {
    MiMCSponge(xL_in: BigNumberish, xR_in: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    'MiMCSponge(uint256,uint256)'(
      xL_in: BigNumberish,
      xR_in: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MiMCSponge(xL_in: BigNumberish, xR_in: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'MiMCSponge(uint256,uint256)'(
      xL_in: BigNumberish,
      xR_in: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
