/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { ethers, EventFilter, Signer, BigNumber, BigNumberish, PopulatedTransaction } from 'ethers';
import { Contract, ContractTransaction, Overrides, CallOverrides } from '@ethersproject/contracts';
import { BytesLike } from '@ethersproject/bytes';
import { Listener, Provider } from '@ethersproject/providers';
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi';

interface IDeployerInterface extends ethers.utils.Interface {
  functions: {
    'deploy(bytes,bytes32)': FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'deploy', values: [BytesLike, BytesLike]): string;

  decodeFunctionResult(functionFragment: 'deploy', data: BytesLike): Result;

  events: {};
}

export class IDeployer extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IDeployerInterface;

  functions: {
    deploy(_initCode: BytesLike, _salt: BytesLike, overrides?: Overrides): Promise<ContractTransaction>;

    'deploy(bytes,bytes32)'(
      _initCode: BytesLike,
      _salt: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  deploy(_initCode: BytesLike, _salt: BytesLike, overrides?: Overrides): Promise<ContractTransaction>;

  'deploy(bytes,bytes32)'(_initCode: BytesLike, _salt: BytesLike, overrides?: Overrides): Promise<ContractTransaction>;

  callStatic: {
    deploy(_initCode: BytesLike, _salt: BytesLike, overrides?: CallOverrides): Promise<string>;

    'deploy(bytes,bytes32)'(_initCode: BytesLike, _salt: BytesLike, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    deploy(_initCode: BytesLike, _salt: BytesLike, overrides?: Overrides): Promise<BigNumber>;

    'deploy(bytes,bytes32)'(_initCode: BytesLike, _salt: BytesLike, overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    deploy(_initCode: BytesLike, _salt: BytesLike, overrides?: Overrides): Promise<PopulatedTransaction>;

    'deploy(bytes,bytes32)'(
      _initCode: BytesLike,
      _salt: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
