/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { IHasher } from "./IHasher";

export class IHasherFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IHasher {
    return new Contract(address, _abi, signerOrProvider) as IHasher;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "in_xL",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "in_xR",
        type: "uint256"
      }
    ],
    name: "MiMCSponge",
    outputs: [
      {
        internalType: "uint256",
        name: "xL",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "xR",
        type: "uint256"
      }
    ],
    stateMutability: "pure",
    type: "function"
  }
];
