/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { ethers, EventFilter, Signer, BigNumber, BigNumberish, PopulatedTransaction } from 'ethers';
import { Contract, ContractTransaction, Overrides, CallOverrides } from '@ethersproject/contracts';
import { BytesLike } from '@ethersproject/bytes';
import { Listener, Provider } from '@ethersproject/providers';
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi';

interface IVerifierInterface extends ethers.utils.Interface {
  functions: {
    'verifyProof(bytes,uint256[6])': FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'verifyProof', values: [BytesLike, BigNumberish[]]): string;

  decodeFunctionResult(functionFragment: 'verifyProof', data: BytesLike): Result;

  events: {};
}

export class IVerifier extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IVerifierInterface;

  functions: {
    verifyProof(_proof: BytesLike, _input: BigNumberish[], overrides?: Overrides): Promise<ContractTransaction>;

    'verifyProof(bytes,uint256[6])'(
      _proof: BytesLike,
      _input: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  verifyProof(_proof: BytesLike, _input: BigNumberish[], overrides?: Overrides): Promise<ContractTransaction>;

  'verifyProof(bytes,uint256[6])'(
    _proof: BytesLike,
    _input: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    verifyProof(_proof: BytesLike, _input: BigNumberish[], overrides?: CallOverrides): Promise<boolean>;

    'verifyProof(bytes,uint256[6])'(
      _proof: BytesLike,
      _input: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    verifyProof(_proof: BytesLike, _input: BigNumberish[], overrides?: Overrides): Promise<BigNumber>;

    'verifyProof(bytes,uint256[6])'(
      _proof: BytesLike,
      _input: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    verifyProof(_proof: BytesLike, _input: BigNumberish[], overrides?: Overrides): Promise<PopulatedTransaction>;

    'verifyProof(bytes,uint256[6])'(
      _proof: BytesLike,
      _input: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
