/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IVerifierInterface extends Interface {
  functions: {
    verifyProof: TypedFunctionDescription<{
      encode([_proof, _input]: [Arrayish, BigNumberish[]]): string;
    }>;
  };

  events: {};
}

export class IVerifier extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IVerifier;
  attach(addressOrName: string): IVerifier;
  deployed(): Promise<IVerifier>;

  on(event: EventFilter | string, listener: Listener): IVerifier;
  once(event: EventFilter | string, listener: Listener): IVerifier;
  addListener(eventName: EventFilter | string, listener: Listener): IVerifier;
  removeAllListeners(eventName: EventFilter | string): IVerifier;
  removeListener(eventName: any, listener: Listener): IVerifier;

  interface: IVerifierInterface;

  functions: {
    verifyProof(
      _proof: Arrayish,
      _input: BigNumberish[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "verifyProof(bytes,uint256[6])"(
      _proof: Arrayish,
      _input: BigNumberish[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  verifyProof(
    _proof: Arrayish,
    _input: BigNumberish[],
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "verifyProof(bytes,uint256[6])"(
    _proof: Arrayish,
    _input: BigNumberish[],
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    verifyProof(
      _proof: Arrayish,
      _input: BigNumberish[],
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "verifyProof(bytes,uint256[6])"(
      _proof: Arrayish,
      _input: BigNumberish[],
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;
  };
}
