/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface MerkleTreeWithHistoryInterface extends Interface {
  functions: {
    FIELD_SIZE: TypedFunctionDescription<{ encode([]: []): string }>;

    ROOT_HISTORY_SIZE: TypedFunctionDescription<{ encode([]: []): string }>;

    ZERO_VALUE: TypedFunctionDescription<{ encode([]: []): string }>;

    currentRootIndex: TypedFunctionDescription<{ encode([]: []): string }>;

    filledSubtrees: TypedFunctionDescription<{
      encode([]: [BigNumberish]): string;
    }>;

    hasher: TypedFunctionDescription<{ encode([]: []): string }>;

    levels: TypedFunctionDescription<{ encode([]: []): string }>;

    nextIndex: TypedFunctionDescription<{ encode([]: []): string }>;

    roots: TypedFunctionDescription<{ encode([]: [BigNumberish]): string }>;

    hashLeftRight: TypedFunctionDescription<{
      encode([_hasher, _left, _right]: [string, Arrayish, Arrayish]): string;
    }>;

    isKnownRoot: TypedFunctionDescription<{
      encode([_root]: [Arrayish]): string;
    }>;

    getLastRoot: TypedFunctionDescription<{ encode([]: []): string }>;

    zeros: TypedFunctionDescription<{ encode([i]: [BigNumberish]): string }>;
  };

  events: {};
}

export class MerkleTreeWithHistory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): MerkleTreeWithHistory;
  attach(addressOrName: string): MerkleTreeWithHistory;
  deployed(): Promise<MerkleTreeWithHistory>;

  on(event: EventFilter | string, listener: Listener): MerkleTreeWithHistory;
  once(event: EventFilter | string, listener: Listener): MerkleTreeWithHistory;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): MerkleTreeWithHistory;
  removeAllListeners(eventName: EventFilter | string): MerkleTreeWithHistory;
  removeListener(eventName: any, listener: Listener): MerkleTreeWithHistory;

  interface: MerkleTreeWithHistoryInterface;

  functions: {
    FIELD_SIZE(overrides?: TransactionOverrides): Promise<BigNumber>;

    "FIELD_SIZE()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    ROOT_HISTORY_SIZE(overrides?: TransactionOverrides): Promise<number>;

    "ROOT_HISTORY_SIZE()"(overrides?: TransactionOverrides): Promise<number>;

    ZERO_VALUE(overrides?: TransactionOverrides): Promise<BigNumber>;

    "ZERO_VALUE()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    currentRootIndex(overrides?: TransactionOverrides): Promise<number>;

    "currentRootIndex()"(overrides?: TransactionOverrides): Promise<number>;

    filledSubtrees(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    "filledSubtrees(uint256)"(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    hasher(overrides?: TransactionOverrides): Promise<string>;

    "hasher()"(overrides?: TransactionOverrides): Promise<string>;

    levels(overrides?: TransactionOverrides): Promise<number>;

    "levels()"(overrides?: TransactionOverrides): Promise<number>;

    nextIndex(overrides?: TransactionOverrides): Promise<number>;

    "nextIndex()"(overrides?: TransactionOverrides): Promise<number>;

    roots(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    "roots(uint256)"(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    /**
     * Hash 2 tree leaves, returns MiMC(_left, _right)
     */
    hashLeftRight(
      _hasher: string,
      _left: Arrayish,
      _right: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    /**
     * Hash 2 tree leaves, returns MiMC(_left, _right)
     */
    "hashLeftRight(address,bytes32,bytes32)"(
      _hasher: string,
      _left: Arrayish,
      _right: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    /**
     * Whether the root is present in the root history
     */
    isKnownRoot(
      _root: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<boolean>;

    /**
     * Whether the root is present in the root history
     */
    "isKnownRoot(bytes32)"(
      _root: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<boolean>;

    /**
     * Returns the last root
     */
    getLastRoot(overrides?: TransactionOverrides): Promise<string>;

    /**
     * Returns the last root
     */
    "getLastRoot()"(overrides?: TransactionOverrides): Promise<string>;

    /**
     * provides Zero (Empty) elements for a MiMC MerkleTree. Up to 32 levels
     */
    zeros(i: BigNumberish, overrides?: TransactionOverrides): Promise<string>;

    /**
     * provides Zero (Empty) elements for a MiMC MerkleTree. Up to 32 levels
     */
    "zeros(uint256)"(
      i: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<string>;
  };

  FIELD_SIZE(overrides?: TransactionOverrides): Promise<BigNumber>;

  "FIELD_SIZE()"(overrides?: TransactionOverrides): Promise<BigNumber>;

  ROOT_HISTORY_SIZE(overrides?: TransactionOverrides): Promise<number>;

  "ROOT_HISTORY_SIZE()"(overrides?: TransactionOverrides): Promise<number>;

  ZERO_VALUE(overrides?: TransactionOverrides): Promise<BigNumber>;

  "ZERO_VALUE()"(overrides?: TransactionOverrides): Promise<BigNumber>;

  currentRootIndex(overrides?: TransactionOverrides): Promise<number>;

  "currentRootIndex()"(overrides?: TransactionOverrides): Promise<number>;

  filledSubtrees(
    arg0: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  "filledSubtrees(uint256)"(
    arg0: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  hasher(overrides?: TransactionOverrides): Promise<string>;

  "hasher()"(overrides?: TransactionOverrides): Promise<string>;

  levels(overrides?: TransactionOverrides): Promise<number>;

  "levels()"(overrides?: TransactionOverrides): Promise<number>;

  nextIndex(overrides?: TransactionOverrides): Promise<number>;

  "nextIndex()"(overrides?: TransactionOverrides): Promise<number>;

  roots(arg0: BigNumberish, overrides?: TransactionOverrides): Promise<string>;

  "roots(uint256)"(
    arg0: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  /**
   * Hash 2 tree leaves, returns MiMC(_left, _right)
   */
  hashLeftRight(
    _hasher: string,
    _left: Arrayish,
    _right: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  /**
   * Hash 2 tree leaves, returns MiMC(_left, _right)
   */
  "hashLeftRight(address,bytes32,bytes32)"(
    _hasher: string,
    _left: Arrayish,
    _right: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  /**
   * Whether the root is present in the root history
   */
  isKnownRoot(
    _root: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<boolean>;

  /**
   * Whether the root is present in the root history
   */
  "isKnownRoot(bytes32)"(
    _root: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<boolean>;

  /**
   * Returns the last root
   */
  getLastRoot(overrides?: TransactionOverrides): Promise<string>;

  /**
   * Returns the last root
   */
  "getLastRoot()"(overrides?: TransactionOverrides): Promise<string>;

  /**
   * provides Zero (Empty) elements for a MiMC MerkleTree. Up to 32 levels
   */
  zeros(i: BigNumberish, overrides?: TransactionOverrides): Promise<string>;

  /**
   * provides Zero (Empty) elements for a MiMC MerkleTree. Up to 32 levels
   */
  "zeros(uint256)"(
    i: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  filters: {};

  estimate: {
    FIELD_SIZE(overrides?: TransactionOverrides): Promise<BigNumber>;

    "FIELD_SIZE()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    ROOT_HISTORY_SIZE(overrides?: TransactionOverrides): Promise<BigNumber>;

    "ROOT_HISTORY_SIZE()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    ZERO_VALUE(overrides?: TransactionOverrides): Promise<BigNumber>;

    "ZERO_VALUE()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    currentRootIndex(overrides?: TransactionOverrides): Promise<BigNumber>;

    "currentRootIndex()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    filledSubtrees(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "filledSubtrees(uint256)"(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    hasher(overrides?: TransactionOverrides): Promise<BigNumber>;

    "hasher()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    levels(overrides?: TransactionOverrides): Promise<BigNumber>;

    "levels()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    nextIndex(overrides?: TransactionOverrides): Promise<BigNumber>;

    "nextIndex()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    roots(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "roots(uint256)"(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    /**
     * Hash 2 tree leaves, returns MiMC(_left, _right)
     */
    hashLeftRight(
      _hasher: string,
      _left: Arrayish,
      _right: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    /**
     * Hash 2 tree leaves, returns MiMC(_left, _right)
     */
    "hashLeftRight(address,bytes32,bytes32)"(
      _hasher: string,
      _left: Arrayish,
      _right: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    /**
     * Whether the root is present in the root history
     */
    isKnownRoot(
      _root: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    /**
     * Whether the root is present in the root history
     */
    "isKnownRoot(bytes32)"(
      _root: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    /**
     * Returns the last root
     */
    getLastRoot(overrides?: TransactionOverrides): Promise<BigNumber>;

    /**
     * Returns the last root
     */
    "getLastRoot()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    /**
     * provides Zero (Empty) elements for a MiMC MerkleTree. Up to 32 levels
     */
    zeros(
      i: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    /**
     * provides Zero (Empty) elements for a MiMC MerkleTree. Up to 32 levels
     */
    "zeros(uint256)"(
      i: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;
  };
}
