// import ArbitrumLogo from '@webb-dapp/apps/configs/logos/chains/ArbitrumLogo';
import GanacheLogo from '@webb-dapp/apps/configs/logos/chains/GanacheLogo';
// import HarmonyLogo from '@webb-dapp/apps/configs/logos/chains/HarmonyLogo';
// import OptimismLogo from '@webb-dapp/apps/configs/logos/chains/OptimismLogo';
// import PolygonLogo from '@webb-dapp/apps/configs/logos/chains/PolygonLogo';
// import ShidenLogo from '@webb-dapp/apps/configs/logos/chains/ShidenLogo';
import WEBBLogo from '@webb-dapp/apps/configs/logos/chains/WebbLogo';
import EtherLogo from '@webb-dapp/apps/configs/logos/Eth';
import {
  AppConfig,
  ChainType,
  EVMChainId,
  InternalChainId,
  SubstrateChainId,
  WebbCurrencyId,
} from '@webb-tools/api-providers';

export const getSupportedCurrenciesOfChain = (chainId: InternalChainId): WebbCurrencyId[] => {
  return chainsConfig[chainId].currencies;
};

export const chainsConfig: AppConfig['chains'] = {
  [InternalChainId.ProtocolSubstrateStandalone]: {
    chainType: ChainType.Substrate,
    id: InternalChainId.ProtocolSubstrateStandalone,
    group: 'webb',
    tag: 'dev',
    chainId: SubstrateChainId.ProtocolSubstrateStandalone,
    logo: WEBBLogo,
    url: 'ws://127.0.0.1:9944',
    name: 'Protocol Substrate Development',
    currencies: [WebbCurrencyId.WEBB, WebbCurrencyId.TEST],
    nativeCurrencyId: WebbCurrencyId.WEBB,
  },
  // [InternalChainId.Rinkeby]: {
  //   chainType: ChainType.EVM,
  //   group: 'eth',
  //   id: InternalChainId.Rinkeby,
  //   chainId: EVMChainId.Rinkeby,
  //   name: 'Rinkeby',
  //   url: 'https://rinkeby.infura.io/v3/e54b7176271840f9ba62e842ff5d6db4',
  //   evmRpcUrls: ['https://rinkeby.infura.io/v3/e54b7176271840f9ba62e842ff5d6db4'],
  //   blockExplorerStub: 'https://rinkeby.etherscan.io',
  //   logo: EtherLogo,
  //   tag: 'test',
  //   currencies: [WebbCurrencyId.ETH, WebbCurrencyId.WETH, WebbCurrencyId.webbWETH],
  //   nativeCurrencyId: WebbCurrencyId.ETH,
  // },
  // [InternalChainId.Ropsten]: {
  //   chainType: ChainType.EVM,
  //   group: 'eth',
  //   id: InternalChainId.Ropsten,
  //   chainId: EVMChainId.Ropsten,
  //   name: 'Ropsten',
  //   url: 'https://ropsten.infura.io/v3/e54b7176271840f9ba62e842ff5d6db4',
  //   evmRpcUrls: ['https://ropsten.infura.io/v3/e54b7176271840f9ba62e842ff5d6db4'],
  //   blockExplorerStub: 'https://ropsten.etherscan.io',
  //   logo: EtherLogo,
  //   tag: 'test',
  //   currencies: [WebbCurrencyId.ETH, WebbCurrencyId.WETH, WebbCurrencyId.webbWETH],
  //   nativeCurrencyId: WebbCurrencyId.ETH,
  // },
  // [InternalChainId.Goerli]: {
  //   chainType: ChainType.EVM,
  //   group: 'eth',
  //   id: InternalChainId.Goerli,
  //   chainId: EVMChainId.Goerli,
  //   name: 'Goerli',
  //   url: 'https://goerli.infura.io/v3/e54b7176271840f9ba62e842ff5d6db4',
  //   evmRpcUrls: ['https://goerli.infura.io/v3/e54b7176271840f9ba62e842ff5d6db4'],
  //   blockExplorerStub: 'https://goerli.etherscan.io',
  //   logo: EtherLogo,
  //   tag: 'test',
  //   currencies: [WebbCurrencyId.ETH, WebbCurrencyId.WETH, WebbCurrencyId.webbWETH],
  //   nativeCurrencyId: WebbCurrencyId.ETH,
  // },
  // [InternalChainId.Kovan]: {
  //   chainType: ChainType.EVM,
  //   group: 'eth',
  //   id: InternalChainId.Kovan,
  //   chainId: EVMChainId.Kovan,
  //   name: 'Kovan',
  //   url: 'https://kovan.infura.io/v3/e54b7176271840f9ba62e842ff5d6db4',
  //   evmRpcUrls: ['https://goerli.infura.io/v3/e54b7176271840f9ba62e842ff5d6db4'],
  //   blockExplorerStub: 'https://kovan.etherscan.io',
  //   logo: KLogo,
  //   tag: 'test',
  //   currencies: [WebbCurrencyId.ETH, WebbCurrencyId.WETH],
  //   nativeCurrencyId: WebbCurrencyId.ETH,
  // },
  // [InternalChainId.OptimismTestnet]: {
  //   chainType: ChainType.EVM,
  //   group: 'eth',
  //   id: InternalChainId.OptimismTestnet,
  //   chainId: EVMChainId.OptimismTestnet,
  //   name: 'Optimism Testnet',
  //   url: 'https://kovan.optimism.io',
  //   evmRpcUrls: ['https://kovan.optimism.io'],
  //   blockExplorerStub: 'https://kovan-optimistic.etherscan.io',
  //   logo: OptimismLogo,
  //   tag: 'test',
  //   currencies: [WebbCurrencyId.ETH, WebbCurrencyId.WETH, WebbCurrencyId.webbWETH],
  //   nativeCurrencyId: WebbCurrencyId.ETH,
  // },
  // [InternalChainId.ArbitrumTestnet]: {
  //   chainType: ChainType.EVM,
  //   group: 'eth',
  //   id: InternalChainId.ArbitrumTestnet,
  //   chainId: EVMChainId.ArbitrumTestnet,
  //   name: 'Arbitrum Testnet',
  //   url: 'https://rinkeby.arbitrum.io/rpc',
  //   evmRpcUrls: ['https://rinkeby.arbitrum.io/rpc'],
  //   blockExplorerStub: 'https://testnet.arbiscan.io',
  //   logo: ArbitrumLogo,
  //   tag: 'test',
  //   currencies: [WebbCurrencyId.ETH, WebbCurrencyId.WETH, WebbCurrencyId.webbWETH],
  //   nativeCurrencyId: WebbCurrencyId.ETH,
  // },
  // [InternalChainId.HarmonyTestnet1]: {
  //   chainType: ChainType.EVM,
  //   group: 'one',
  //   id: InternalChainId.HarmonyTestnet1,
  //   chainId: EVMChainId.HarmonyTestnet1,
  //   name: 'Harmony Testnet Shard 1',
  //   tag: 'test',
  //   url: 'https://api.s1.b.hmny.io',
  //   evmRpcUrls: ['https://api.s1.b.hmny.io'],
  //   logo: HarmonyLogo,
  //   currencies: [WebbCurrencyId.ONE],
  //   nativeCurrencyId: WebbCurrencyId.ONE,
  // },
  // [ChainId.HarmonyTestnet0]: {
  // chainType: ChainType,
  //   group: 'one',
  //   id: ChainId.HarmonyTestnet0,
  //   evmId: EVMChain.HarmonyTestnet0,
  //   name: 'Harmony Testnet Shard 0',
  //   tag: 'test',
  //   url: 'https://api.s0.b.hmny.io',
  //   evmRpcUrls: ['https://api.s0.b.hmny.io'],
  //   logo: HarmonyLogo,
  //   currencies: [
  //     {
  //       currencyId: WebbCurrencyId.ONE,
  //       enabled: true,
  //     },
  //   ],
  //   nativeCurrencyId: WebbCurrencyId.ONE,
  // },
  // [InternalChainId.HarmonyMainnet0]: {
  //   chainType: ChainType.EVM,
  //   group: 'one',
  //   id: InternalChainId.HarmonyMainnet0,
  //   chainId: EVMChainId.HarmonyMainnet0,
  //   name: 'Harmony Mainnet Shard 0',
  //   tag: 'live',
  //   url: 'https://api.harmony.one',
  //   evmRpcUrls: ['https://api.harmony.one'],
  //   logo: HarmonyLogo,
  //   currencies: [WebbCurrencyId.ONE],
  //   nativeCurrencyId: WebbCurrencyId.ONE,
  // },
  // [ChainId.EthereumMainNet]: {
  // chainType: ChainType,
  //   group: 'eth',
  //   id: ChainId.EthereumMainNet,
  //   evmId: EVMChain.EthereumMainNet,
  //   name: 'Ethereum mainnet',
  //   tag: 'live',
  //   url: 'https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161',
  //   evmRpcUrls: ['https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161'],
  //   logo: EtherLogo,
  //   currencies: [
  //     {
  //       currencyId: WebbCurrencyId.ETH,
  //       enabled: true,
  //     },
  //   ],
  //   nativeCurrencyId: WebbCurrencyId.ETH,
  // },
  // [InternalChainId.Shiden]: {
  //   chainType: ChainType.EVM,
  //   group: 'sdn',
  //   id: InternalChainId.Shiden,
  //   chainId: EVMChainId.Shiden,
  //   name: 'Shiden',
  //   tag: 'live',
  //   url: 'https://shiden.api.onfinality.io/public',
  //   evmRpcUrls: ['https://shiden.api.onfinality.io/public'],
  //   blockExplorerStub: 'https://shiden.subscan.io',
  //   logo: ShidenLogo,
  //   currencies: [WebbCurrencyId.SDN],
  //   nativeCurrencyId: WebbCurrencyId.SDN,
  // },
  // [InternalChainId.PolygonTestnet]: {
  //   chainType: ChainType.EVM,
  //   group: 'matic',
  //   id: InternalChainId.PolygonTestnet,
  //   chainId: EVMChainId.PolygonTestnet,
  //   name: 'Polygon Testnet',
  //   tag: 'test',
  //   url: 'https://rpc-mumbai.maticvigil.com/',
  //   evmRpcUrls: ['https://rpc-mumbai.maticvigil.com/'],
  //   blockExplorerStub: 'https://mumbai.polygonscan.com/',
  //   logo: PolygonLogo,
  //   currencies: [WebbCurrencyId.MATIC, WebbCurrencyId.WETH, WebbCurrencyId.webbWETH],
  //   nativeCurrencyId: WebbCurrencyId.MATIC,
  // },
  [InternalChainId.HermesLocalnet]: {
    chainType: ChainType.EVM,
    group: 'eth',
    id: InternalChainId.HermesLocalnet,
    chainId: EVMChainId.HermesLocalnet,
    name: 'Hermes Localnet',
    tag: 'dev',
    url: 'http://127.0.0.1:5001',
    evmRpcUrls: ['http://127.0.0.1:5001'],
    logo: GanacheLogo,
    currencies: [WebbCurrencyId.webbDEV, WebbCurrencyId.DEV, WebbCurrencyId.ETH],
    nativeCurrencyId: WebbCurrencyId.ETH,
  },
  [InternalChainId.AthenaLocalnet]: {
    chainType: ChainType.EVM,
    group: 'eth',
    id: InternalChainId.AthenaLocalnet,
    chainId: EVMChainId.AthenaLocalnet,
    name: 'Athena Localnet',
    tag: 'dev',
    url: 'http://127.0.0.1:5002',
    evmRpcUrls: ['http://127.0.0.1:5002'],
    logo: GanacheLogo,
    currencies: [WebbCurrencyId.webbDEV, WebbCurrencyId.DEV, WebbCurrencyId.ETH],
    nativeCurrencyId: WebbCurrencyId.ETH,
  },
  [InternalChainId.DemeterLocalnet]: {
    chainType: ChainType.EVM,
    group: 'eth',
    id: InternalChainId.DemeterLocalnet,
    chainId: EVMChainId.DemeterLocalnet,
    name: 'Demeter Localnet',
    tag: 'dev',
    url: 'http://127.0.0.1:5003',
    evmRpcUrls: ['http://127.0.0.1:5003'],
    logo: GanacheLogo,
    currencies: [WebbCurrencyId.webbDEV, WebbCurrencyId.DEV, WebbCurrencyId.ETH],
    nativeCurrencyId: WebbCurrencyId.ETH,
  },
  // [InternalChainId.DkgSubstrateStandalone]: {
  //   chainType: ChainType.SubstrateDevelopment,
  //   id: InternalChainId.DkgSubstrateStandalone,
  //   group: 'webb',
  //   tag: 'dev',
  //   chainId: SubstrateChainId.DkgSubstrateStandalone,
  //   logo: WEBBLogo,
  //   url: 'ws://127.0.0.1:9944',
  //   name: 'Webb Development',
  //   currencies: [WebbCurrencyId.WEBB],
  //   nativeCurrencyId: WebbCurrencyId.WEBB,
  // },
  [InternalChainId.EggStandalone]: {
    chainType: ChainType.Substrate,
    id: InternalChainId.EggStandalone,
    group: 'webb',
    tag: 'test',
    chainId: SubstrateChainId.EggStandalone,
    logo: WEBBLogo,
    url: 'wss://standalone.webb.tools',
    name: 'Webb Eggnet',
    currencies: [WebbCurrencyId.WEBB],
    nativeCurrencyId: WebbCurrencyId.WEBB,
  },
};
