blank_issues_enabled: true
contact_links:
  - name: Tangle Network Telegram
    url: https://t.me/tangletnet
    about: Please ask questions here.
  - name: Tangle Network Discord Server
    url: https://discord.com/invite/cv8EfJu3Tn
    about: Please ask and answer questions here.
  - name: Tangle Feedback Discussion
    url: https://github.com/tangle-network/feedback/discussions/categories/dapp-feedback
    about: Please provide feedback and discussion here.
