FROM node:gallium-alpine

ARG NAME_PROJECT=${NAME_PROJECT}
ARG NAME_BRIDGE_DAPP=${NAME_BRIDGE_DAPP}
ARG NAME_STATS_DAPP=${NAME_STATS_DAPP}
ARG PORT_BRIDGE_DAPP=${PORT_BRIDGE_DAPP}
ARG PORT_STATS_DAPP=${PORT_STATS_DAPP}

ARG PATH_PROJECT=/app/${NAME_PROJECT}

ENV PATH=${PATH_PROJECT}/node_modules/.bin:$PATH

WORKDIR ${PATH_PROJECT}

COPY package.json yarn.lock ./

RUN apk update && apk add --update git python3 make g++ \
  && rm -rf /var/cache/apk/*

RUN yarn

COPY . .

EXPOSE ${PORT_BRIDGE_DAPP}
EXPOSE ${PORT_STATS_DAPP}

CMD tail -f /dev/null
