FROM node:gallium-alpine

ARG PATH_PROJECT=/usr/local/${NAME_PROJECT}
ARG PATH1=${PATH_PROJECT}/node_modules/.bin
ARG PATH2=${PATH_PROJECT}/apps/${NAME_BRIDGE_DAPP}/node_modules/.bin
ARG PATH3=${PATH_PROJECT}/apps/${NAME_STATS_DAPP}/node_modules/.bin

ENV PATH=${PATH1}:${PATH2}:${PATH3}:$PATH

WORKDIR ${PATH_PROJECT}

COPY package.json .

RUN yarn

COPY . .

EXPOSE ${PORT_BRIDGE_DAPP}
EXPOSE ${PORT_STATS_DAPP}

CMD tail -f /dev/null
