declare module '@tangle-network/sandbox-ui/primitives' {
  export {
    Avatar,
    AvatarFallback,
    Badge,
    Button,
    type ButtonProps,
    Card,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
    CodeBlock,
    type CodeBlockProps,
    CopyButton,
    Dialog,
    DialogClose,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
    EmptyState,
    type EmptyStateProps,
    InlineCode,
    type InlineCodeProps,
    Input,
    type InputProps,
    Label,
    SegmentedControl,
    type SegmentedControlOption,
    type SegmentedControlProps,
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
    Skeleton,
    SkeletonCard,
    SkeletonTable,
    StatCard,
    type StatCardProps,
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
    Tabs,
    TabsContent,
    TabsList,
    TabsTrigger,
    TangleKnot,
    Textarea,
    type TextareaProps,
    ToastProvider,
  } from '@tangle-network/sandbox-ui';
}
