[build]
  publish = "dist/apps/leaderboard"
  command = "yarn nx build leaderboard"

  # If the branch is not master, continue the build process
  # If the branch is master, check if the project's CHANGELOG.md file has changed
  # If the CHANGELOG.md file has changed, continue the build process,
  # Otherwise, stop the build process
  ignore = "[ \"$BRANCH\" != \"master\" ] && exit 1 || git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- apps/leaderboard/CHANGELOG.md && exit 0 || exit 1"
