export enum BadgeEnum {
  VALIDATOR = 'VALIDATOR',
  RESTAKE_DEPOSITOR = 'RESTAKE_DEPOSITOR',
  RESTAKE_DELEGATOR = 'RESTAKE_DELEGATOR',
  LIQUID_STAKER = 'LIQUID_STAKER',
  NATIVE_RESTAKER = 'NATIVE_RESTAKER',
  OPERATOR = 'OPERATOR',
}
