export enum BadgeEnum {
  VALIDATOR = 'VALIDATOR',
  RESTAKE_DEPOSITOR = 'RESTAKE_DEPOSITOR',
  RESTAKE_DELEGATOR = 'RESTAKE_DELEGATOR',
  LIQUID_STAKER = 'LIQUID_STAKER',
  NATIVE_RESTAKER = 'NATIVE_RESTAKER',
  OPERATOR = 'OPERATOR',
  BLUEPRINT_OWNER = 'BLUEPRINT_OWNER',
  SERVICE_PROVIDER = 'SERVICE_PROVIDER',
  JOB_CALLER = 'JOB_CALLER',
}
