import { StandardMerkleTree } from '@openzeppelin/merkle-tree';
import { getAddress, type Hex } from 'viem';
import {
  buildCreditsLeaf,
  getCreditsWindow,
  loadCreditsTreeData,
  verifyCreditsClaim,
  verifyCreditsProof,
} from './merkleTree';

describe('credits merkle tree', () => {
  it('verifies a merkle proof generated by StandardMerkleTree', () => {
    const epochId = '1';
    const account = getAddress('0x000000000000000000000000000000000000dEaD');
    const amount = '1000000000000000000';

    const tree = StandardMerkleTree.of(
      [
        [epochId, account, amount],
        ['1', getAddress('0x000000000000000000000000000000000000bEEF'), '42'],
      ],
      ['uint256', 'address', 'uint256'],
    );

    const proof = tree.getProof(0) as Hex[];
    const root = tree.root as Hex;
    const leaf = buildCreditsLeaf(BigInt(epochId), account, BigInt(amount));

    expect(verifyCreditsProof(root, leaf, proof)).toBe(true);
    expect(
      verifyCreditsClaim(root, {
        account,
        epochId: BigInt(epochId),
        amount: BigInt(amount),
        merkleProof: proof,
        root,
      }),
    ).toBe(true);
  });

  it('rejects invalid proofs', () => {
    const epochId = '2';
    const account = getAddress('0x000000000000000000000000000000000000dEaD');
    const amount = '10';

    const tree = StandardMerkleTree.of(
      [[epochId, account, amount]],
      ['uint256', 'address', 'uint256'],
    );

    const root = tree.root as Hex;
    const proof = tree.getProof(0) as Hex[];

    const badLeaf = buildCreditsLeaf(2n, account, 11n);
    expect(verifyCreditsProof(root, badLeaf, proof)).toBe(false);
  });

  it('parses time-windowed credits metadata', () => {
    const payload = {
      epochId: '1',
      root: '0x01',
      totalValue: '0',
      entryCount: 0,
      startTs: '100',
      endTs: '200',
      epochSeconds: '100',
      tntToken: '0x0000000000000000000000000000000000000001',
      creditsPerTnt: '5',
      entries: {},
    };

    const data = loadCreditsTreeData(JSON.stringify(payload));
    const window = getCreditsWindow(data);

    expect(window?.startTs).toBe(100n);
    expect(window?.endTs).toBe(200n);
    expect(window?.epochSeconds).toBe(100n);
    expect(window?.tntToken).toBe(payload.tntToken);
    expect(window?.creditsPerTnt).toBe(5n);
  });
});
