import '@webb-tools/webb-ui-components/tailwind.css';

export const metadata = {
  title: 'Welcome to testnet-leaderboard',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
