name: Master
on:
  push:
    branches:
      - master

jobs:
  bump-version:
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    strategy:
      matrix:
        step: ['bump-version']
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: ${{ matrix.step }}
      env:
        GH_PAGES_SRC: packages/apps/build
        GH_PAT: ${{ secrets.GH_PAT }}
        GH_RELEASE_GITHUB_API_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        yarn ${{ matrix.step }}
